version: '2'

services:
  db:
    image: postgis/postgis:12-master
    restart: always
    environment: 
        - POSTGRES_USER=daniel
        - POSTGRES_PASSWORD=supersecretpassword
        - ALLOW_IP_RANGE=0.0.0.0/0
        - POSTGRES_DBNAME=postgres
    ports:
        - "5432:5432"
  guamapa_api:
    restart: always
    environment:
      - DJANGO_SECRET_KEY=local
      - POSTGRES_USER=daniel
      - POSTGRES_DBNAME=postgres
      - POSTGRES_PASSWORD=supersecretpassword
    build: ./
    command: >
      bash -c "python wait_for_postgres.py &&
               ./manage.py migrate &&
               ./manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  pgadmin:
    image: dpage/pgadmin4:latest
    environment: 
      - PGADMIN_DEFAULT_EMAIL=daniel@danielrb.dev
      - PGADMIN_DEFAULT_PASSWORD=popo
    ports:
      - "5050:80"