# Generated by Django 3.1.5 on 2021-01-14 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20171227_2246'),
        ('users', '0002_auto_20210114_1922'),
    ]

    operations = [
    ]
