# Generated by Django 3.1.5 on 2021-01-26 00:25

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('elevation', models.PositiveIntegerField(blank=True, null=True)),
                ('population', models.PositiveIntegerField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='AssistantMayor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('occupation', models.CharField(blank=True, max_length=200)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Masculine'), ('F', 'Feminine'), ('O', 'Other')], max_length=1)),
                ('activity', models.CharField(blank=True, max_length=200)),
                ('ethnicity', models.CharField(blank=True, max_length=200)),
                ('education', models.CharField(blank=True, max_length=200)),
                ('other_info', models.TextField(blank=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('appointment_date', models.DateField(blank=True, null=True)),
                ('term_duration', models.DurationField(blank=True, null=True)),
                ('town', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='towns.town')),
            ],
        ),
    ]
