# Generated by Django 3.1.5 on 2021-01-23 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('towns', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='town',
            old_name='coordinates',
            new_name='location',
        ),
    ]
