# Generated by Django 3.1.5 on 2021-01-17 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('towns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='town',
            name='name',
            field=models.CharField(default='default town name', max_length=200),
            preserve_default=False,
        ),
    ]
