name: Continuous Integration and Delivery

on: [push]

env:
  GUAMAPA_API_IMAGE: docker.pkg.github.com/$GITHUB_REPOSITORY/api:latest
  NGINX_IMAGE: docker.pkg.github.com/$GITHUB_REPOSITORY/nginx:latest
  VIRTUAL_HOST: guamapa-api.lacasaamber.com
  VIRTUAL_PORT: 8000
  LETSENCRYPT_HOST: guamapa-api.lacasaamber.com
  DEFAULT_EMAIL: daniel@danielrb.dev
  ACME_CA_URI: https://acme-staging-v02.api.letsencrypt.org/directory
  NGINX_PROXY_CONTAINER: nginx-proxy

jobs:

  build:
    name: Build Docker Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v1
      - name: Add environment variables to .env
        run: |
          echo DEBUG=0 >> .env
          echo DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }} >> .env
          echo POSTGRES_DBNAME=${{ secrets.POSTGRES_DBNAME}} >> .env
          echo POSTGRES_USER=${{ secrets.POSTGRES_USER}} >> .env
          echo POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD}} >> .env
          echo ALLOW_IP_RANGE=${{ secrets.ALLOW_IP_RANGE}} >> .env
          echo PGADMIN_DEFAULT_EMAIL=${{ secrets.PGADMIN_DEFAULT_EMAIL}} >> .env
          echo PGADMIN_DEFAULT_PASSWORD=${{ secrets.PGADMIN_DEFAULT_PASSWORD}} >> .env
          echo PGADMIN_DEFAULT_PASSWORD=${{ secrets.PGADMIN_DEFAULT_PASSWORD}} >> .env
          echo VIRTUAL_HOST=${{ env.VIRTUAL_HOST }} >> .env
          echo VIRTUAL_PORT=${{ env.VIRTUAL_PORT }} >> .env
          echo LETSENCRYPT_HOST=${{ env.LETSENCRYPT_HOST }} >> .env
          echo DEFAULT_EMAIL=${{ env.DEFAULT_EMAIL }} >> .env
          echo ACME_CA_URI=${{ env.ACME_CA_URI }} >> .env
          echo NGINX_PROXY_CONTAINER=${{ env.NGINX_PROXY_CONTAINER }} >> .env
          echo PRODUCTION=True >> .env
          echo DJANGO_ALLOWED_HOSTS='["guamapa-api.lacasaamber.com", "guamapa.lacasaamber.com"]' >> .env
          echo GUAMAPA_API_IMAGE=${{ env.GUAMAPA_API_IMAGE }}
      - name: Set environment variables
        run: |
          echo GUAMAPA_API_IMAGE=${{ env.GUAMAPA_API_IMAGE }} >> $GITHUB_ENV
          echo NGINX_IMAGE=${{ env.NGINX_IMAGE }} >> $GITHUB_ENV
      - name: Log in to GitHub Packages
        run: echo ${GITHUB_TOKEN} | docker login -u ${GITHUB_ACTOR} --password-stdin docker.pkg.github.com
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Pull images
        run: |
          docker pull ${{ env.GUAMAPA_API_IMAGE }} || true
          docker pull ${{ env.NGINX_IMAGE }} || true
      - name: Build images
        run: |
          docker build -f ./Dockerfile.prod -t  ${{ env.GUAMAPA_API_IMAGE }} .  || true
          docker build -f ./nginx/Dockerfile -t ${{ env.NGINX_IMAGE }} ./nginx  || true
      - name: Push images
        run: |
          docker push ${{ env.GUAMAPA_API_IMAGE }}
          docker push ${{ env.NGINX_IMAGE }}
  deploy:
    name: Deploy to DigitalOcean
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout main
        uses: actions/checkout@v1
      - name: Add environment variables to .env
        run: |
          echo GUAMAPA_API_IMAGE=${{ env.GUAMAPA_API_IMAGE }} >> .env
          echo NGINX_IMAGE=${{ env.NGINX_IMAGE }} >> .env
          echo DEBUG=0 >> .env
          echo DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }} >> .env
          echo POSTGRES_DBNAME=${{ secrets.POSTGRES_DBNAME}} >> .env
          echo POSTGRES_USER=${{ secrets.POSTGRES_USER}} >> .env
          echo POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD}} >> .env
          echo ALLOW_IP_RANGE=${{ secrets.ALLOW_IP_RANGE}} >> .env
          echo PGADMIN_DEFAULT_EMAIL=${{ secrets.PGADMIN_DEFAULT_EMAIL}} >> .env
          echo PGADMIN_DEFAULT_PASSWORD=${{ secrets.PGADMIN_DEFAULT_PASSWORD}} >> .env
          echo VIRTUAL_HOST=${{ env.VIRTUAL_HOST }} >> .env
          echo VIRTUAL_PORT=${{ env.VIRTUAL_PORT }} >> .env
          echo LETSENCRYPT_HOST=${{ env.LETSENCRYPT_HOST }} >> .env
          echo DEFAULT_EMAIL=${{ env.DEFAULT_EMAIL }} >> .env
          echo ACME_CA_URI=${{ env.ACME_CA_URI }} >> .env
          echo NGINX_PROXY_CONTAINER=${{ env.NGINX_PROXY_CONTAINER }} >> .env
          echo GUAMAPA_API_IMAGE=${{ env.GUAMAPA_API_IMAGE }}
          echo PRODUCTION=True >> .env
          echo DJANGO_ALLOWED_HOSTS='["guamapa-api.lacasaamber.com", "guamapa.lacasaamber.com"]' >> .env
      - name: Add the private SSH key to the ssh-agent
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p ~/.ssh
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          ssh-add - <<< "${{ secrets.PRIVATE_KEY }}"
      - name: Build and deploy images on DigitalOcean
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          scp  -o StrictHostKeyChecking=no -r ./.env ./docker-compose.prod.yml root@${{ secrets.DIGITAL_OCEAN_IP_ADDRESS }}:/app
          ssh -o StrictHostKeyChecking=no root@${{ secrets.DIGITAL_OCEAN_IP_ADDRESS }} << 'ENDSSH'
            cd /app
            source .env
            docker login docker.pkg.github.com -u brleinad -p ${{ secrets.GITHUB_TOKEN }}
            docker pull $GUAMAPA_API_IMAGE
            docker pull $NGINX_IMAGE
            docker-compose -f docker-compose.prod.yml up -d
          ENDSSH